export { Navbar } from './navbar'
export { Hero } from './hero'
export { Education } from './education'
export { Experience } from './experience'
export { Skills } from './skills'
export { Contact } from './contact'
export { Footer } from './footer'
